import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
  const [questions, setQuestions] = useState([]);
  useEffect(() => {
    getQuestions();
  }, []);

  const getQuestions = async () => {
    const response = await fetch(
      "https://opentdb.com/api.php?amount=10&category=18&difficulty=easy&type=multiple"
    );
    const tempQuestions = await response.json();
    setQuestions(tempQuestions.results);
  };


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
        questions &&
        questions.map((item, index) =>

                    <li key = {index} >
                    
                    <label style = {{color: '#000'}} > 
                    { decodeURIComponent(item.question)} 
                    </label> 
                    </li>

                )
      }
     
    </div>
  )
}
